### ISSUE TITLE
Can not show /map and /scan topic

### ISSUE THREAD

**Issue by TriKnight** [LdwgWffnschmdt/vue-ros3djs#1]
Hi! Thank for open the code vue-ros3djs. I am following your instruction but get stuck when I try to subscribe topics /map and /scan, the 3D viewer does not show anything. But all the topic have already published via websocket.
![rqt_graph](https://i.ibb.co/4JN50TG/vueapp1.png)
![3D Map show](https://i.ibb.co/TrzzS9n/rosvue.png)
My code
```
<template>
<div class="VueRos3djsDemo">
 <ros3d-viewer
    :ros="ros"
    ref="viewer" id="viewer"
    @hook:mounted="rosViewerMounted" 
    v-if="connected">

    <ros3d-axes />

    <ros3d-grid :numCells = '10' />
    <ros3d-arrow :x ="1" :y="1" :z="1"/>
    <ros3d-occupancy-grid-client />
    <ros3d-laser-scan />
  </ros3d-viewer  >
  </div>
</template>
```
All the topic available in the list bellow

```
/client_count
/connected_clients
/map
/map_metadata
/rosout
/rosout_agg
/scan
/statistics
/tf2_web_republisher/cancel
/tf2_web_republisher/feedback
/tf2_web_republisher/goal

```
Could you help me! Many thanks.

**Comment by LdwgWffnschmdt** [comment]
It is possible, that you need to have the transforms topic `/tf` published. The `<ros3d-viewer>` takes an argument called `fixedFrame` that defaults to `/map` as base frame for all transforms. Try publishing the transforms as well and maybe adjust that fixed frame.

**Comment by TriKnight** [comment]
Thank for your support, I did it.
Bes regards
